### ISSUE TITLE
Draft PR Workflow Trigger

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1077]
## Value Statement

**As** an Engineer
**I want to** have no unexpected triggers on my draft PRs
**So that** we don't introduce bugs into our pipeline and slow down collaboration/iteration

## Acceptance Criteria

**GIVEN** I push a change to my branch on a draft PR
**THEN** the associated actions won't trigger
**UNTIL** the PR is published and ready for review and the appropriate tests

## Checklist

-   [ ] updated our triggered action for pull requests with an if statement negating draft PRs

## How to complete this ticket:
Here's an example using YAML syntax:
```
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR state
      if: github.event.pull_request.draft != true
      run: echo "This is a non-draft pull request. Continuing with the build..."

    # Add your build steps here
```

In this example, the step Check PR state will run a simple shell command that echoes a message if the pull request is not a draft. If the pull request is a draft, this step will be skipped and the workflow will not continue.
