### ISSUE TITLE
Regression Suite Run on Deploy

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1526]
## User Story - Business Need
We need to run the regression suite in all lower environments upon deploy, so we can catch issues before a production deployment.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** business owner
**I want** quality checks built into the deployment pipeline
**So that** the platform can automatically detect and raise issues before changes get to Production

### Additional Info and Resources

- Work was attempted on this in #1327, however there was an issue with using github runner and public endpoints which resulted in timeouts and failure. This was rolled back and canceled until further work could be done on this.
- The Edge team manages the edge routers - the routers through which all VA network traffic from the internet enters our network.
- Example of deployment status reported to slack
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2FnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--266c484afe37fe53f0d3c761e3ca9e931973e803/image.png)

## Engineering Checklist

- [x] Open a ticket with Edge
- [x] Determine if there are alternatives to how runner is being used or an alternative to runner if that isn't going to work
- [x] We need to run the regression from these API actions against the private endpoints
    - [x] Deploy to ENV action .github/workflows/dev_deploy.yml
    - [x] Tag Push to Perf .github/workflows/tag_trigger.yml
    - [x] Pre-release to Staging .github/workflows/prerelease_trigger.yml
- [x] This action needs to be modified or removed and replaced
.github/workflows/regression-public.yml

## Acceptance Criteria

GIVEN the deployment is triggered to env DEV/STAGING/PERF

**This work was not included in this ticket:**
- [ ] Regression run with errors
WHEN the regression suite completes successfully, but returns errors
THEN report the update to slack in `va-notify-automatic-alerts` channel with a status of `Regression Failed`
AND further details can be found in the linked workflow

</br>

**This work was not included in this ticket:**
- [ ] Regression run success
WHEN the regression suite completes successfully with no errors
THEN report the update to slack in `va-notify-automatic-alerts` channel with a status of `Regression Passed`
AND further details can be found in the linked workflow

</br>

**This work was not included in this ticket:**
- [ ] Regression run technical failure
WHEN the regression suite fails to complete
THEN report the update to slack in `va-notify-automatic-alerts` channel with a status of `Regression Error`
AND further details can be found in the linked workflow

</br>

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [x] the regression runs and reports out its status when the Deploy to Env API action is used for dev, perf, staging
- [x] the regression runs and reports out its status when the tag Push to Perf action is used
- [ ] the regression runs and reports out its status when the pre-Release trigger deploys code to Staging

## Potential Dependencies
It is preferred to use the private endpoints.

If we can only use the GitHub runner space to run the code and running it against the public routes, then we are dependent on Edge resolving whatever issue is causing timeouts at the Edge routers for the public endpoints

It is recommended to not use self-hosted runners in public repos.

## Out of Scope

We haven't yet discussed advanced deployment logic, like a rollback, when the regression suite fails, so for now the deployment will complete regardless or regression suite failure.

For full reporting of output (not truncated results) we might need to wait until the html report is created and stashed as an artifact in GitHub. See [Spike](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api-qa/87). So, truncated output should not be a blocker.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1526?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by mjones-oddball** [comment]
We set this to an 8 because both Cris and Lucas will be working on this together. They are hoping it's only 3ish days, but ya never know.

**Comment by cris-oddball** [comment]
Lucas and I agreed to pick this up on Monday

**Comment by ldraney** [comment]
Me and Cris synced on this.  She discovered that using a self-hosted runner with a public repo is fine, so long as we follow some security practices that shouldn't be an issue in our case.  That enough for me to move forward on investigating if we can simply add the public repo to the self-hosted runner, and what that would entail.  It's important I don't disrupt work that is currently using the runner, so I'm hoping for a clear answer without needing to play with our current runner. 

If there's a path forward, I will need to update the runner at some point, so I'll coordinate with QA and team at that point.

**Comment by ldraney** [comment]
From [the self-hosted runner documentation](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners):

> You can add self-hosted runners at various levels in the management hierarchy:
> - Repository-level runners are dedicated to a single repository.
> - Organization-level runners can process jobs for multiple repositories in an organization.
> - Enterprise-level runners can be assigned to multiple organizations in an enterprise account.

Which means we need to add an organization-level runner if we want it to be accessible by both repos.  
As our organization is department-of-veterans-affairs, we may have some issues with that; but I pinged another DevOps engineer (Jeremy) to hear his thoughts.  I may end up messaging the oddball-va channel to be sure!  
That's not a likely possibility, so now I'm going to investigate using a PAT (rather than deploy_keys, which has already been attempted) for repo to repo communication.  As long as this allows for a beautiful workflow_call at the end of our deploy_to_env workflow to regression-public.yml, I'll be happy with this solution.

**Comment by ldraney** [comment]
I'll send this comment to @cris-oddball and @k-macmillan to see if things look good.  If so, I'll ask Kyle to add the PAT to our repo as `QA_REPO_ACCESS_TOKEN`.  

I can use a self-hosted runner for our private repository in our public repository's workflow via a `workflow_call`, assuming we have the Personal Access Token (PAT) set up. Here's how I can approach this.  Btw, this is a fairly strong hypothesis/approach, based on docs and another oddball engineer (Jeremy), who will be reading this tomorrow morning as well:

1. **Reusable Workflows**: I can use a reusable workflow by another workflow if it's in the same repository, stored in a public repository (and our organization allows using public reusable workflows), or stored in a private repository (with settings that allow it to be accessed). More information can be found in [GitHub Docs on Reusable Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).

2. **Accessing Self-Hosted Runners used by another repo**: Called workflows that are owned by the same user or organization as the caller workflow can access self-hosted runners from the caller's context. This means a called workflow can access self-hosted runners that are in the caller repository or in the caller repository's organization, provided that the runner has been made available to the caller repository. Detailed information is available on the same [GitHub Docs page](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-self-hosted-runners).

3. **Calling a Reusable Workflow**: To call a reusable workflow, I'll use the `uses` keyword within a job. I can reference reusable workflow files using the syntax `{owner}/{repo}/.github/workflows/{filename}@{ref}` for workflows in public and private repositories. The `{ref}` can be a SHA, a release tag, or a branch name. 

4. **The best security practices** for this are outlined in [GitHub Docs on Security Hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#reusing-third-party-workflows).  When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN. For more information about the github context, see [Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).  I’m not sure what this implies yet, but it seems to basically be saying that a public repo now has access to the private repo’s actions’ permissions, so be wise. 

5. **Passing Inputs and Secrets**: For inputs, the data type of the input value must match the type specified in the called workflow (either boolean, number, or string). Workflows calling reusable workflows in the same organization or enterprise can use the `inherit` keyword to implicitly pass the secrets, as detailed in [GitHub Docs on Passing Inputs and Secrets to a Reusable Workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow).  

With the above outline, I can leverage our self-hosted runner in our private repository for workflows in our public repository, using `workflow_call` and properly configured PAT in our secrets. This approach ensures secure and efficient workflow management across different repository types within our organization.

### Workflow File Example

#### Notification-api (public repo) Workflow proposal:

```yaml
name: Trigger Regression Tests

on: [push, pull_request]  # Define your trigger events

jobs:
  call-regression-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call Regression Testing Workflow
        uses: department-of-veterans-affairs/notification-api-qa/.github/workflows/run-regression-tests.yml@master
        with:
          environment: ${{ input.env }}'  
          branch: ${{ github.ref }}  # Use the current branch
        secrets:
          VAEC_AWS_ACCESS_KEY_ID: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          VAEC_AWS_SECRET_ACCESS_KEY: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          VAEC_DEPLOY_ROLE: ${{ secrets.VAEC_DEPLOY_ROLE }}
          QA_REPO_ACCESS_TOKEN: ${{ secrets.QA_REPO_ACCESS_TOKEN }}
```

- The `QA_REPO_ACCESS_TOKEN` is used to authenticate access to the private repository.
- The `environment` and `branch` inputs are passed to run-regression-tests, as it needs..

## Security and Best Practices
- The use of `QA_REPO_ACCESS_TOKEN` ensures secure access to the private repository.
- I didn’t end up using the secrets.inheret because in this case it makes more sense to be explicit.

**Comment by cris-oddball** [comment]
Yea, the peter-evans repository-dispatch was what I was looking at, too. i'll re-read my note to see if I actually found something that did not require a 3rd party workflow.

**Comment by ldraney** [comment]
***
No, no, I think my original format was correct.  An example from the same documentation (Again, I'm concerned about how the PAT is going to be used):
```
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
```

Time to make a POC in my own repo!

**Comment by ldraney** [comment]
Okay, I keep getting this error:
```
Invalid workflow file: .github/workflows/test-workflow-call-pvt.yml#L8
error parsing called workflow
".github/workflows/test-workflow-call-pvt.yml"
-> "ldraney/private-repo/.github/workflows/private-workflow.yml@master"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```
Here's my code in my public repo:
```
name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

jobs:
  reusable_workflow_job:
    uses: ldraney/private-repo/.github/workflows/pizza-workflow.yml@master
    secrets:
      envPAT: ${{ secrets.envPAT }}
```
here's the code in my private repo:
```
name: Hello World Workflow

on:
  workflow_call:
    secrets:
      envPAT:
        required: true
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World! The workflow has been successfully triggered."
```
Which isn't too surprising at this point :(.  [The documentation says](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-from-your-private-repository#sharing-actions-and-workflows-from-your-private-repository):
> Configure the repository to allow access to workflows in other private repositories.

Also, the settings explicitly say:
<img width="1838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGcwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--404f80d430f7d8328522657e0a9690c4ee10d801/image.png" alt="image.png" />

**Comment by ldraney** [comment]
I'm going to make sure by doing the same set up with a private repo instead of public, won't take long. 

Then, since workflow_call doesn't work, the next best result in our timeframe would be to provide a link in the workflow to the regression suite; but this won't report the passed/failed regression.  This is what I'm thinking about.

**Comment by ldraney** [comment]
Cris and I decided to approach the [repository dispatch option](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) before approaching a second self-hosted runner.  I will follow the model outlined in [this third-part action](https://github.com/marketplace/actions/repository-dispatch) in my own repos first to see if the end result is what we want.  If so, we will likely use the third-party action as a model for proper use of the respository_dispatch trigger, as it seems the marketplace version isn't much more than a template configuration.

**Comment by ldraney** [comment]
Just recording here that I got a successful repository_dispatch hello world with the following code in my personal repos:
public repo:
```
name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

# jobs:
#   reusable_workflow_job:
#     uses: ldraney/private-repo/.github/workflows/private-workflow.yml@master
jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.envPAT }}" -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "trigger-private-workflow"}' \
          https://api.github.com/repos/ldraney/private-repo/dispatches  
```
private repo:
```
name: Hello World Workflow

on:
  workflow_call:
    secrets:
      envPAT:
        required: true
  workflow_dispatch: 
  repository_dispatch:
    types: [trigger-private-workflow]    

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World! The workflow has been successfully triggered."
```

**Comment by cris-oddball** [comment]
Some thoughts... This is good work. We will meet in the morning to discuss

1. have the workflow wait until the regression is done (likelywith the gh cli)
2. meanwhile, has a link to the currently running workflow
3. Once regression completes, the action recognizes either a passed or failed regression (likely with the gh cli)
4. retrieve an artifact URL from the QA repo regression output if user wants to see regression results.

Let's look into this [trigger-workflow-and-wait](https://github.com/convictional/trigger-workflow-and-wait) action as well, though.

For your step #4, we might need to create that HTML report and use that as the artifact.

**Comment by ldraney** [comment]
Got the first part of the above working with:
public repo:
```
name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.envPAT }}" -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "trigger-private-workflow", "client_payload": {"environment": "${{ github.event.inputs.environment }}"}' \
          https://api.github.com/repos/ldraney/private-repo/dispatche
```
private repo:
```
name: Hello World Workflow

on:
  repository_dispatch:
    types: [trigger-private-workflow]    

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World from ${{ github.event.client_payload.environment }}! The workflow has been successfully triggered."
```

So I'll now check out [trigger-workflow-and-wait](https://github.com/convictional/trigger-workflow-and-wait) before syncing with Cris.

**Comment by ldraney** [comment]
Successful run with the following code:
public repo:
```
name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest  # specify the runner
    name: first job
    steps:
    - name: Trigger Workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: ldraney
        repo: private-repo
        github_token: ${{ secrets.envPAT }}
        # github_user: github-user
        workflow_file_name: private-workflow.yml
        ref: master
        wait_interval: 1
        client_payload: '{"environment": "${{ github.event.inputs.environment }}"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
```

**Comment by ldraney** [comment]
Me and Cris successfully got the new action to work!  
But, it's a third party action.  Thankfullly, its only seven files, and has a lenient MIT licensing that Cris will handle the dynamics of.  So, i'll be moving this all over to notification-api... after I run one more thing setup -- getting a link to the exact regression that ran with this deployment.

**Comment by ldraney** [comment]
Hey Cris,  
 
I’ve made branch 1526-regression-deploy and updated it with what is working in [my public repo](https://github.com/ldraney/public-repo/actions). 

You can see the changes [on the PR here](https://github.com/department-of-veterans-affairs/notification-api/pull/1565).  You can see I’ve added new files according to [the repo we copied here](https://github.com/Enrico-Infrinity/trigger-workflow-and-wait/tree/patch-1).  

*probably don’t have to worry about this*, but I had some trouble adding these and getting them working in my own repo.  I beat my head against this for hours.  I was extremely frustrated with what should have been a simple copy paste.  I’m 90% sure once a repo is git cloned, it is then registered as a submodule, and i had to rename the directory i cloned it into to get it working in my public repo.  You’ll like have to do something similar.  The new files appear on the draft PR, so again you probably don't have to worry about this. 

Things left to do:

1. [Test the workflow](https://github.com/department-of-veterans-affairs/notification-api/actions/workflows/dev_deploy.yml) and make sure it works.  Since the workflow is not on master, be sure to select it from our branch: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenREQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff469f380c8d80b4c2973f631b1bf51f33f3ba3e/image.png" alt="image.png" />
- master, in this case, means branch of notification-api that will be tested.  
- As you will see in the `run-regression.yml`, this input for the branch will influence which branch of the QA repo, in other words, which version of the regression will run.

2. MIT stuff, as you mentioned. 
3. Make sure things are as you like.  I believe this will be working solution!  Here’s hoping for smooth testing. 

some notes:

* Workflow_dispatch means there will be an interface for the workflow like the one above.  
* Workflow_call is what enables the run_regression to appear as its nice own block on the actions workflow progress graphic \

**Comment by cris-oddball** [comment]
today was consumed with testing Ed's lambda changes and then refactoring the QA repo to use the new secrets.

i will review what Lucas has and see if there is anything I can do from here.

**Comment by cris-oddball** [comment]
> As you will see in the run-regression.yml, this input for the branch will influence which branch of the QA repo, in other words, which version of the regression will run.

Turning my attention back to this - if what Lucas said above is true, then this will not work. In the API workflows (actions) the branch is meant to indicate the branch of the API that gets deployed, not what branch in the QA repo runs. I'll pull the code down and take a look to see if this is true. If it is, I'll try to modify it such that it always runs master in the QA repo (which is its own problem but there you go).

**Comment by cris-oddball** [comment]
Merged master into this branch to capture the recent changes.

Yes, that workflow passes the branch to the QA repo, which we do not want.

Will run the workflow to see if it even runs the regression. If it does, will then try to modify the thing so that it does not send the branch over to the QA repo.

**Comment by cris-oddball** [comment]
this is also a problem: `FROM alpine:3.15.0` in `.github/actions/workflow-trigger-and-wait/Dockerfile` We do not want another outdated container.

**Comment by cris-oddball** [comment]
Trying to run the Deploy to Dev action using the workflow from the branch Lucas created resulted immediately in 
```

Invalid workflow file: .github/workflows/dev_deploy.yml#L71
The workflow is not valid. .github/workflows/dev_deploy.yml (Line: 71, Col: 11): Input branch is required, but not provided while calling.

```

**Comment by cris-oddball** [comment]
commented out these lines from run-regression.yml

```
on: 
  workflow_call:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging)'
        required: true
        type: string
      # branch:
        # description: 'Will run latest SHA from branch'
        # default: 'master'
        # required: false
        # type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging)'
        required: true
        type: string
      # branch:
        # description: 'Will run latest SHA from branch'
        # default: 'master'
        # required: false
        # type: string
```

and hardcoded the branch of the regression suite to run
```
jobs:
  trigger-regression-tests:
    runs-on: ubuntu-latest  # specify the runner
    name: Trigger Regression Tests
    steps:
    - name: Trigger Regression Workflow
      uses: ./.github/actions/workflow-trigger-and-wait
      with:
        owner: department-of-veterans-affairs
        repo: notification-api-qa
        github_token: ${{ secrets.envPAT }}
        workflow_file_name: regression.yml
        ref: ${{ github.event.inputs.branch }}
        wait_interval: 10
        client_payload: '{"environment": "${{ github.event.inputs.environment }}", "branch": "master"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
```

and now the action is at least [deploying the api](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7173375454) to dev

**Comment by cris-oddball** [comment]
Failed to trigger the regression:
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c669bf61bc030e53859128b279b9ba8abc9da2e/Screenshot%202023-12-11%20at%202.16.16%E2%80%AFPM.jpg" alt="Screenshot 2023-12-11 at 2.16.16 PM.jpg" />

Probably because I deployed master and master doesn't have any of that stuff. So, good thing I yanked the branch out of the call over to run regression since the QA suite wouldn't know what to do with that branch anyway.

Redeploying with the branch set to the 1526 branch.

**Comment by cris-oddball** [comment]
also, those failures are not being reported back to Slack, looks like only `setup-env-{env}` and `deploy-api` steps get reported out to slack?

<img width="1816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1432bfbcfe36e3d3c6ef25ed56885fe7368de5e/Screenshot%202023-12-11%20at%202.20.59%E2%80%AFPM.jpg" alt="Screenshot 2023-12-11 at 2.20.59 PM.jpg" />

**Comment by cris-oddball** [comment]
Same result on Trigger Regression Workflow, even when deploying from the workflow and the branch.
<img width="1451" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b70f71366c9889a7f8e941e7a70a4e0da4b38c2d/Screenshot%202023-12-11%20at%202.32.35%E2%80%AFPM.jpg" alt="Screenshot 2023-12-11 at 2.32.35 PM.jpg" />

Looking into error.

**Comment by cris-oddball** [comment]
Progress? Adding 
```
jobs:
  trigger-regression-tests:
    runs-on: ubuntu-latest  # specify the runner
    name: Trigger Regression Tests
    steps:
    - uses: actions/checkout@v4 # added this line
```
Does get [farther](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7173706044/job/19533865794) but the new error is 
```
Error: Github token is required. You can head over settings and
under developer, you can create a personal access tokens. The
token requires repo access.
```
So, yea, need to add the PAT.  Holding off until speaking with Kyle.

**Comment by cris-oddball** [comment]
Confirmed that I do not have access to create a PAT for the QA Repo, so will wait and talk to Kyle. 

Also cleaned up some edges in the PR.

**Comment by cris-oddball** [comment]
Spoke with Kyle:
- OK to use PAT since we don't really have a choice, when ready Kyle will set that up (I do not have permissions)
- Kyle needs to know the explicit permissions to set on the PAT
- NOT OK to use the currently copied action code. We need to go back to the CURL solution, make sure we get some output to return in the public workflow (link to the QA private workflow showing the results or to an HTML report artifact

Given that, marking this ticket as blocked until Lucas returns and dropping it back into the TODO column. I will sync with Lucas when he returns next week.

cc / @ldraney @npmartin-oddball @mjones-oddball @k-macmillan

**Comment by k-macmillan** [comment]
I am able to make a fine-grained PAT that the dept of veteran's affairs owns.

**Comment by cris-oddball** [comment]
The [comment](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1526#issuecomment-1841714371) shows the code that uses CURL. If I have time I'll see if I can't get that going with a PAT Kyle creates.

**Comment by cris-oddball** [comment]
**FRIDAY UPDATE**

I have a proof of concept working in my public and private personal repos that is documented [here](https://docs.google.com/document/d/1XMZMmmN-t7DNx4kU04wEdcN-9a0mENQxI0_I2XQv06M/edit?usp=sharing).

Kyle and Lucas have access to my private repo now and both are linked in that document. 

The fine-grained permissions are also described in that document.

Lucas uses the CURL method while mine uses a GitHub scripting action (from GitHub and verified). The latter may be more extensible given that it is a script and there is a ping/pong method described in the document that might also be of use.

I will get with @ldraney on Monday to review our options and consider next steps.

**Comment by k-macmillan** [comment]
PAT made and added to the API repo that has access to the QA repo.

**Comment by ldraney** [comment]
Me and Cris had a meeting to go over the details. 
My POC copied a bash script from an existing public action, but Cris reported that was shut down by Kyle due to... security concerns?  The script seems safe enough to me, so may ping Kyle about that. 
Cris has a cleaner approach though (as there are things in the script that don't directly pertain to this ticket), so I will first respect Kyle's input and see if I can get the same results in her POC repos.

**Comment by ldraney** [comment]
Still just letting this sit.  Cris did some cool things with her POC.  

but, in summary, all thats left to figure out it:
1. Public repo needs to detect failure in called workflow
2. Public repo should get a beautiful, easy to see report from the private repo’s regression

**Comment by ldraney** [comment]
There’s nothing in [github-script](https://github.com/actions/github-script?tab=readme-ov-file) that offers what we need, so next step is probably to look closer at what I originally copied over to get the functionality that we want; 

So essentially, I'll look at that copied action's script and re-write it specifically for our purposes... and then see how/if I'll implement it with what Cris already has.

**Comment by ldraney** [comment]
I just made a branch on Cris’ POC repo to play with her workflow file. 

The final solution will be a renamed `regression-public.yml` to `run-regression.yml` in notification-api repo.  It will have a nice looking action step that looks something like this (shoutout to Cris for refining this):
```
    - name: Trigger Regression Workflow
      uses: ./.github/actions/workflow-trigger-and-wait
      with:
        owner: department-of-veterans-affairs
        repo: notification-api-qa
        github_token: ${{ secrets.envPAT }}
        workflow_file_name: regression.yml
        ref: ${{ github.event.inputs.branch }}
        wait_interval: 10
        client_payload: '{"environment": "${{ github.event.inputs.environment }}", "branch": "master"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
```
Which will use the action.yml and trigger_script.sh which reside in the workflow-trigger-and-wait directory, as shown above.  

**Hypothesized Next Steps**

1. **Finalize `trigger_script.sh`**:
   - Implement the logic to continuously check the workflow's status until completion.
   - Handle the extraction of the workflow run URL and the final status (success or failure).
   - Go over any needed error handling and/or security practices in the script. 
 

2. **Update `action.yml`**:
   - Define the inputs and outputs for the custom action, matching it with the `trigger_script.sh`.
   - Ensure the action metadata aligns with the GitHub Actions requirements.

3. **Testing in the POC Public Repository**:
   - Deploy the changes to the public repository and test the entire workflow.
   - Monitor the actions dashboard in both `hello-world` and `hello-universe` to verify the integration behaves as expected.

4. **Test in the POC Public Repository**:
   - Hopefully just a few renaming of script inputs is all that is needed here. 

And, we’ll get to that point. It might be ready to open for a PR after another discussion with Cris at that point.
