### ISSUE TITLE
Github Actions - Environment as type `environment`

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1611]
## User Story - Business Need
This change allows us to configure advanced features by environment, such as protection rules and secrets. When a workflow job references an environment, the job won't start until all of the environment's protection rules pass. A job also cannot access secrets that are defined in an environment until all the deployment protection rules pass.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** developer and maintainer of the notification API
**I want** to explicitly declare `type: environment` in our GitHub workflow inputs
**So that** we can move toward continuous deployment with the flexibility this allows.

### Additional Info and Resources

Current workflow input example:
```
on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (dev|perf|staging|prod)"
        default: dev
        required: true
```

Proposed change:
```
    inputs:
      environment:
        type: environment
        description: "Deployment environment (dev|perf|staging|prod)"
        default: dev
        required: true
```

Adding `type: environment` to our GitHub workflows involves several intricate aspects we need to consider to ensure a smooth transition:

1. **Workflow Compatibility**: The change in `type` from an implicit string to an explicit `environment` might affect workflows in ways we haven't anticipated. We need to review all workflows that interact with the `environment` variable to ensure they can handle this new type. This is crucial since any discrepancy can lead to workflow failures.

2. **Downstream Effects on QA Processes**: The `run-regression.yml` file, which utilizes the `environment` variable as a string, might be particularly impacted. This could necessitate changes in our QA processes, especially if the `environment` type affects how variables are passed and interpreted in test scripts.

Relevant documentation links:
- [Workflow Syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype)
- [Using Environments for Deployment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)
- [Github Action Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)

## Engineering Checklist
- [ ] Update GitHub workflow input to include `type: environment`.
- [ ] Ensure compatibility of the new `environment` type with existing workflows.
- [ ] Test and observe any unexpected consequences, especially in `run-regression.yml` and the called regression in notification-api-qa.

## Acceptance Criteria

- The `environment` input in GitHub workflows should now explicitly declare `type: environment`.
- All workflows that use or pass the environment variable should be adjusted and change tested accordingly. This includes the following files in the .github/workflows directory:
    - db-downgrade.yml
    - dev_deploy.yml
    - release_trigger.yml
    - run-regression.yml
    - deployment.yml
    - build.yml
    - prerelease_trigger.yml
    - deploy_lambda_dev.yml
    - lambda-functions.yml
    - tag_trigger.yml
    - release.yml
    - load-test-sms-response-time.yaml (communication with QA on this one)
- This ticket does not include the following workflows that are not actively used (as using and testing these workflows is outside the scope of this ticket):
    - load-test-email-delivery-time.yaml
    - test-github-actions.yml

- The QA repo's environment flag should continue to work correctly after this change.

## QA Considerations
- [ ] work with developer to understand and mitigate any impacts this may have on triggering the regression
- [ ] if needed update the QA repo with any changes needed to facilitate this change; if needed, spin up a new ticket to manage that work.

**Comment by mjones-oddball** [comment]
@ldraney Friendly reminder! Please don't delete sections you don't believe you need like QA considerations. If you want to hide them simply use the comment out option.

Can you please update the Acceptance Criteria referenced below, to detail which workflows will need to be validated and any relevant actions to take related to that which = success?

> All workflows that use or pass the environment variable should be adjusted accordingly.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1611?planning-poker) with Zenhub @cris-oddball @edDocMe360 @EvanParish @k-macmillan @kalbfled @ldraney

**Comment by ldraney** [comment]
Work on the QA workflows first to see if there are additional unknowns that will affect the work on this ticket.

**Comment by ldraney** [comment]
Noting here the changes should essentially be:
Everywhere we cast the environment to a string, we remove the following syntax (except the qa repo call):
```
  run-deployment:
    needs: [setup-environment, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "${{ inputs.environment }}"
      ref: "${{ needs.setup-environment.outputs.git-hash }}"
    secrets: inherit
  run-deployment:
    needs: [setup-environment, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: inputs.environment
      ref: "${{ needs.setup-environment.outputs.git-hash }}"
    secrets: inherit
```
