### ISSUE TITLE
BUG: new Deploy Release action only regresses Perf

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1818]
## Description

During the OOC Staging/Prod release on 5/23, it was discovered that the new Deploy Release action (.github/workflows/deploy-release.yml) only runs the Perf regression (the default when no environment is passed in). The worfklow should properly set the environment for the run-qa-suite step.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Use this action to deploy to an environment that is not Perf. Notice that the regression ran in Perf (follow the resultant workflow link to the regression).
2. Also notice that it could not interpret the environment that was being passed in, which is why it defaulted to running in Perf.

## Workaround
We have to remember to run either the Staging or Prod regression manually when using this action to release code.

## Impact/Urgency
High

## Expected Behavior

- [x] When I use the Deploy Action to send a release to staging and/or Prod, then the action runs the QA Suite against the correct environment.

## QA Considerations
- [x] Confirm the expected behavior - a deploy to dev should be sufficient.

## Additional Info & Resources

The code block for the run-qa-suite should be as follows, not what it is.
```
  run-qa-suite:
    needs: [run-deployment]
    uses: ./.github/workflows/run-regression.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
```
