### ISSUE TITLE
Copy Lighthouse templates from Lighthouse service to va.gov service

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#347]
# Value Statement
**As** a Lighthouse Business Line customer
**I want to** my templates to temporarily live on the va.gov service
**So that** I can use the VANotify service in vets-api code base

# Acceptance Criteria
**GIVEN** the Lighthouse template is called
**WHEN** an app is connected or disconnected from a Veteran's profile
**THEN** the template used will be apart of va.gov service

# Checklist
- [x] Create in Dev
- [x] Create in Staging
- [x] Create in Production

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by ffafara-tw** [comment]
I copied Lighthouse templates to va.gov service in all environments. Below is the info:

<details><summary>Development</summary>

```yaml
- id: 7c9811af-7665-45be-a60d-fee576b1091d
   template_type: "email"
   name: "Lighthouse - On Application Disconnect "
   subject: "Your VA profile is disconnected from ((application))."
   content: "Dear ((first_name)),\n\nYour VA profile was disconnected from ((application)) on ((time)). This app can't access any new information from your VA.gov profile, but some apps may still store information you've already shared. To learn about how this application stores your information, including what information it stores, if any, and what steps are available to you, review ((application))'s [privacy policy](((privacy_policy))).\n\nIf you did not perform this disconnection, you may manage your [connected apps](https://www.va.gov/profile/connected-applications). We also advise you to [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\nva.gov\n___\nYou are receiving this email because you disconnected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov.",

- id: d6f1ec0f-c131-46d9-80b0-e8d3efc4703d
   template_type: "email"
   name: "Lighthouse - On Application Connect"
   subject: "Your VA profile is connected to ((application))."
   content: "Dear ((first_name)),\n\nYour VA profile was connected to ((application)) on ((time)).\n You can learn about how this application stores your information by reviewing its [privacy policy](((privacy_policy))).\n\nIf you did not perform this connection, you may disconnect from the application on our [connected applications page](https://www.va.gov/profile/connected-applications). We also advise you to [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\nva.gov\n___\nYou are receiving this email because you connected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov."
```
</details>
