### ISSUE TITLE
Update GitHub Actions "set-output" and "set-state"

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#861]
## Issue

`set-output` is being [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). 

Follow GitHub's guidance and update our actions accordingly.

## Checklist

-   [ ] `set-state` replaced
-   [ ] `set-output` replaced
-   [ ] Variables referenced correctly with new `{{ env.<variable name> }}`
  - [Example](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-1)

## Additional Information
Current example:
```yaml

    outputs:
      git-hash: ${{ steps.set-hash.outputs.commit-hash }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set Hash
        id: set-hash
        run: |
          echo "::set-output name=commit-hash::"$(git rev-parse HEAD)""
```

Change example:
```yaml

    outputs:
      git-hash: ${{ env.commit-hash }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set Hash
        id: set-hash
        run: |
          echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_ENV
```
Warning GitHub gives us:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/c770d427-1b69-4071-96e4-09c1f3d157b8)
